Add support for version comment field
fastly/terraform-provider-fastly pull request #139
Opened 2019-04-01 18:37 UTC by philippschulte

This solves #126.

2019-04-10 00:38 UTC, chenrui333 reviewed
👍

2019-04-22 19:28 UTC, chenrui333 commented
I think we can merge this now, right? 😄

2019-06-11 13:13 UTC, trentrosenbaum approved these changes
This PR address the following issues https://github.com/terraform-providers/terraform-provider-fastly/issues/126

From here I can see that an alteration in the go-fastly client has been released in version 0.4.3
https://github.com/fastly/go-fastly/issues/102 and https://github.com/fastly/go-fastly/pull/103

2019-06-11 14:11 UTC, trentrosenbaum requested changes
I have added a comment about the name being used to set the comment value.

2019-06-11 14:11 UTC, trentrosenbaum commented on fastly/resource_fastly_service_v1.go
> +		Comment: d.Get("name").(string),
This looks like the wrong field value is being used and the same is present in another PR addressing comments.

2019-06-11 14:11 UTC, trentrosenbaum commented on fastly/resource_fastly_service_v1.go
> +		Comment: d.Get("name").(string),
The name field in the data is being used to populate the comment field on the input.

2019-06-20 15:59 UTC, philippschulte commented
I'll close this one in favor of #169.

2019-06-20 15:59 UTC, closed without merging