Update director backends if changed
fastly/terraform-provider-fastly pull request #197
Opened 2019-10-30 11:38 UTC by phamann

### TL;DR
This attempts to address #143 by ensuring we re-create the backend to director relationship when a backend changes. However the solution is non-ideal, see below for further information.

## Why?
As the provider uses a `schema.TypeSet` set as the type for the `backend` field, we cannot cleanly determine whether a backend has been updated versus being added. Therefore, it simply deletes any backends in the change set and adds them again. See lines. (Note: this seems to be the convention for most collection based fields on the service resource.)

When the backend is deleted, this also propagates the delete through the models relationships and thus deletes the backend from the director. 

Therefore, we have multiple options to solve this problem:\

1) Refactor the provider to use `schema.List` as the `backend` field type, which will allow us to safely detect updates and use the appropriate `gofastly.UpdateBackend` API client call. This will ensure the backend isn't dereferenced from the director. However, this is a breaking change and should be considered as a wider refactor to update other fields to also use `TypeList`.
2) Attempt to determine the updates in the change set using the `backend.name` property. However this is brittle as doesn't account for changes to the backend name itself.
3) If there are backend changes, iterate over the directors on the service version and re-create the relationship if the backend name matches a backend in the change set.

This PR has implemented *option 3* above, however I don't feel comfortable with the change and therefore would like to open discussion here for wider consensus.

2019-10-31 00:34 UTC, thommahoney approved these changes
The code reads quite confusingly but I think that's just because I'm not a very experienced Gopher. This solution will work as a stopgap ahead of options (1) or (2). I'd be interested to see what the `List` implementation looks like.

2019-10-31 13:19 UTC, sbfaulkner commented
work-around: rename my backends any time that I update their configuration, so it correctly re-adds the "new" backends to the director(s), avoiding the problem

2019-10-31 13:22 UTC, sbfaulkner commented
since I have a work-around, I'd lean towards fixing "correctly" ... not 100% sure it requires a breaking change though... perhaps it can instead be managed with an approach that uses a smarter diff function instead of just using Set's Difference in the appropriate places?

related to the use of the List type instead, is this actually a breaking change? what makes it so... the way a Set is persisted in state vs a list?

2019-10-31 13:23 UTC, sbfaulkner commented
> Attempt to determine the updates in the change set using the backend.name property. However this is brittle as doesn't account for changes to the backend name itself.

isn't the backend name the actual "id" for the director backend anyway? as such, I'm not 100% convinced it's "brittle" -- seems like a rename *should* be a delete and re-add perhaps? (and seems to work as per my work-around)

2019-11-13 19:20 UTC, sbfaulkner commented
@phamann did you (or anyone else) ha e further thoughts about this?

2020-02-20 15:51 UTC, phamann commented
@sbfaulkner, @thom, @philippschulte et.al. Apologies for letting this one slip, I've now had some time to think about this a bit more and take in @sbfaulkner's good points regarding the backend name being the identifier.

I've now refactored my code to use Option 2 above, which is much cleaner and doesn't require the backend update logic to also update directors (which wasn't nice) and therefore much happier with the result.

The TL;DR is we now iterate over the set differences to determine which are genuine additions (new backend name) and which are updates (backend name existed previously). This in turn allows use to call `gofastly.UpdateBackend()`which won't remove the backend from the director and thus solves the original issue in #143.

Have pushed up for review from y'all and will run acceptance tests now.

2020-02-25 14:21 UTC, sbfaulkner commented
approach looks reasonable, but I don't think tests are passing - have not debugged at all on my end

2020-02-25 20:09 UTC, sbfaulkner commented
eg.
```
			hashName := func(v interface{}) int {
				bf := v.(map[string]interface{})
				return hashcode.String(bf["name"].(string))
			}

			oldOnes := schema.NewSet(hashName, obs.List())
			newOnes := schema.NewSet(hashName, nbs.List())

			for ai, abRaw := range newOnes.Difference(oldOnes).List() {
				log.Printf("[DEBUG] add[%v] : %+v\n", ai, abRaw)
			}
			for ui, ubRaw := range newOnes.Intersection(oldOnes).List() {
				log.Printf("[DEBUG] update[%v] : %+v\n", ui, ubRaw)
			}
			for ri, rbRaw := range oldOnes.Difference(newOnes).List() {
				log.Printf("[DEBUG] remove[%v] : %+v\n", ri, rbRaw)
			}
```

2020-03-27 19:13 UTC, philippschulte requested changes
I am fine with your approach when it is working. You should think about applying this to all Fastly resources of `fastly_service_v1`!  As @sbfaulkner already mentioned some acceptance tests are failing. I didn't dig into it but I can say that they are failing because of the changes introduced in this PR. The problem is that for some tests there are dangling backends in the state! The failing tests for Syslog have been addressed in #212.

You can find the complete output of the acceptance tests below:

<details><summary>Acceptance Test Results</summary>
<p>

```bash
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v  -timeout 120m -ldflags="-X=github.com/terraform-providers/terraform-provider-fastly/version.ProviderVersion=acc"
?   	github.com/terraform-providers/terraform-provider-fastly	[no test files]
=== RUN   TestUserAgentContainsProviderVersion
--- PASS: TestUserAgentContainsProviderVersion (0.00s)
=== RUN   TestAccFastlyIPRanges
--- PASS: TestAccFastlyIPRanges (1.63s)
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestResourceFastlyFlattenAclEntries
--- PASS: TestResourceFastlyFlattenAclEntries (0.00s)
=== RUN   TestAccFastlyServiceAclEntriesV1_create
--- PASS: TestAccFastlyServiceAclEntriesV1_create (33.34s)
=== RUN   TestAccFastlyServiceAclEntriesV1_update
--- PASS: TestAccFastlyServiceAclEntriesV1_update (69.86s)
=== RUN   TestAccFastlyServiceAclEntriesV1_update_additional_fields
--- PASS: TestAccFastlyServiceAclEntriesV1_update_additional_fields (72.56s)
=== RUN   TestAccFastlyServiceAclEntriesV1_delete
--- FAIL: TestAccFastlyServiceAclEntriesV1_delete (69.89s)
    testing.go:569: Step 1 error: After applying this step and refreshing, the plan was not empty:

        DIFF:

        UPDATE: fastly_service_v1.foo
          acl.#:                           "1" => "1"
          acl.0.acl_id:                    "76OmXD8nI9fgH67dQiwhAq" => "76OmXD8nI9fgH67dQiwhAq"
          acl.0.name:                      "ACL z88ivvthdx" => "ACL z88ivvthdx"
          activate:                        "true" => "true"
          active_version:                  "2" => "2"
          backend.#:                       "2" => "1"
          backend.0.address:               "9gz.aws.amazon.com" => "9gz.aws.amazon.com"
          backend.0.auto_loadbalance:      "true" => "true"
          backend.0.between_bytes_timeout: "10000" => "10000"
          backend.0.connect_timeout:       "1000" => "1000"
          backend.0.error_threshold:       "0" => "0"
          backend.0.first_byte_timeout:    "15000" => "15000"
          backend.0.healthcheck:           "" => ""
          backend.0.max_conn:              "200" => "200"
          backend.0.max_tls_version:       "" => ""
          backend.0.min_tls_version:       "" => ""
          backend.0.name:                  "tf -test backend" => "tf -test backend"
          backend.0.override_host:         "" => ""
          backend.0.port:                  "80" => "80"
          backend.0.request_condition:     "" => ""
          backend.0.shield:                "" => ""
          backend.0.ssl_ca_cert:           "" => ""
          backend.0.ssl_cert_hostname:     "" => ""
          backend.0.ssl_check_cert:        "true" => "true"
          backend.0.ssl_ciphers:           "" => ""
          backend.0.ssl_client_cert:       "" => ""
          backend.0.ssl_client_key:        "" => ""
          backend.0.ssl_hostname:          "" => ""
          backend.0.ssl_sni_hostname:      "" => ""
          backend.0.use_ssl:               "false" => "false"
          backend.0.weight:                "100" => "100"
          backend.1.address:               "kkt.aws.amazon.com" => ""
          backend.1.auto_loadbalance:      "true" => ""
          backend.1.between_bytes_timeout: "10000" => ""
          backend.1.connect_timeout:       "1000" => ""
          backend.1.error_threshold:       "0" => ""
          backend.1.first_byte_timeout:    "15000" => ""
          backend.1.healthcheck:           "" => ""
          backend.1.max_conn:              "200" => ""
          backend.1.max_tls_version:       "" => ""
          backend.1.min_tls_version:       "" => ""
          backend.1.name:                  "tf-testing-backend" => ""
          backend.1.override_host:         "" => ""
          backend.1.port:                  "80" => ""
          backend.1.request_condition:     "" => ""
          backend.1.shield:                "" => ""
          backend.1.ssl_ca_cert:           "" => ""
          backend.1.ssl_cert_hostname:     "" => ""
          backend.1.ssl_check_cert:        "true" => ""
          backend.1.ssl_ciphers:           "" => ""
          backend.1.ssl_client_cert:       "" => ""
          backend.1.ssl_client_key:        "" => ""
          backend.1.ssl_hostname:          "" => ""
          backend.1.ssl_sni_hostname:      "" => ""
          backend.1.use_ssl:               "false" => ""
          backend.1.weight:                "100" => ""
          bigquerylogging.#:               "0" => "0"
          blobstoragelogging.#:            "0" => "0"
          cache_setting.#:                 "0" => "0"
          cloned_version:                  "2" => "2"
          comment:                         "Managed by Terraform" => "Managed by Terraform"
          condition.#:                     "0" => "0"
          default_host:                    "" => ""
          default_ttl:                     "3600" => "3600"
          dictionary.#:                    "0" => "0"
          director.#:                      "0" => "0"
          domain.#:                        "1" => "1"
          domain.0.comment:                "tf-testing-domain" => "tf-testing-domain"
          domain.0.name:                   "fastly-test.tf-724ebdcz30.com" => "fastly-test.tf-724ebdcz30.com"
          dynamicsnippet.#:                "0" => "0"
          force_destroy:                   "true" => "true"
          gcslogging.#:                    "0" => "0"
          gzip.#:                          "0" => "0"
          header.#:                        "0" => "0"
          healthcheck.#:                   "0" => "0"
          id:                              "7cWNUaNRK8Vl7V9WNIFBOz" => "7cWNUaNRK8Vl7V9WNIFBOz"
          logentries.#:                    "0" => "0"
          name:                            "tf-test-93ubr2z7z7" => "tf-test-93ubr2z7z7"
          papertrail.#:                    "0" => "0"
          request_setting.#:               "0" => "0"
          response_object.#:               "0" => "0"
          s3logging.#:                     "0" => "0"
          snippet.#:                       "0" => "0"
          splunk.#:                        "0" => "0"
          sumologic.#:                     "0" => "0"
          syslog.#:                        "0" => "0"
          vcl.#:                           "0" => "0"
          version_comment:                 "" => ""



        STATE:

        fastly_service_v1.foo:
          ID = 7cWNUaNRK8Vl7V9WNIFBOz
          provider = provider.fastly
          acl.# = 1
          acl.0.acl_id = 76OmXD8nI9fgH67dQiwhAq
          acl.0.name = ACL z88ivvthdx
          activate = true
          active_version = 2
          backend.# = 2
          backend.0.address = 9gz.aws.amazon.com
          backend.0.auto_loadbalance = true
          backend.0.between_bytes_timeout = 10000
          backend.0.connect_timeout = 1000
          backend.0.error_threshold = 0
          backend.0.first_byte_timeout = 15000
          backend.0.healthcheck =
          backend.0.max_conn = 200
          backend.0.max_tls_version =
          backend.0.min_tls_version =
          backend.0.name = tf -test backend
          backend.0.override_host =
          backend.0.port = 80
          backend.0.request_condition =
          backend.0.shield =
          backend.0.ssl_ca_cert =
          backen [...]

2020-09-02 12:04 UTC, phamann commented
Fixed in #304

2020-09-02 12:04 UTC, closed without merging