Fix setting default_ttl to 0 on create
fastly/terraform-provider-fastly pull request #205
Opened 2020-01-17 21:08 UTC by spiralman

This change allows a service to be created with a  `default_ttl` of `0`, fixing #204.

The problem was that, for integer values, the "old" value in the `ResourceData` is `0`, meaning that, if the "new" value is `0`, `HasChange(key)` returns `false`.

It didn't seem possible to override this behavior, either by modifying the "old" value in the `ResourceData` or by specifying a `CustomizeDiff` function (which appears to only be able to *remove* differences, not add ones that wouldn't, otherwise, be detected). Note: if there *is* a way to accomplish this, and that is the preferred method to fix these issues, let us know and we can update the PR.

Instead, we have added an explicit check for the `default_ttl` being set to `0` on service creation and we force the update call to be made, in that case.

We aren't very familiar with the tools available inside the Terraform Plugin SDK, so we may have missed a better solution. Please let us know if there's a better way to fix this issue.

2020-01-20 15:36 UTC, spiralman commented
@philippschulte Not sure what the procedure is for requesting code review in this project, but it seems like you are the primary maintainer. Do you think we could get this into the next release, if you're OK with the solution?

2020-01-21 14:19 UTC, phamann requested changes
:+1: Thank you for your contribution @spiralman I'm happy with the implementation. Only one minor request around adding a comment to explain why the logic exists.

2020-01-21 14:19 UTC, phamann commented on fastly/resource_fastly_service_v1.go
> +		if d.HasChange("default_host") || d.HasChange("default_ttl") || (d.Get("default_ttl") == 0 && initialVersion) {
Can you please add a comment above this explaining why the third conditional exists.

2020-01-21 15:32 UTC, spiralman commented
@phamann Thanks for the review! Updated the PR with a code comment explaining why the check is necessary. Thanks!

2020-01-21 15:34 UTC, phamann approved these changes
👍 LGTM

2020-01-22 15:22 UTC, spiralman commented
@phamann Thanks for the review! Is there anything else necessary to get this merged and into a release? 

Currently, this bug is hindering our ability to roll out some new services in Fastly. We'd rather not have to build some sort of automation on top of Terraform (i.e. run `apply` twice) to work around the bug, if we can get a fix out relatively soon.

Please let me know if there's anything else we can do to help.

2020-01-22 16:20 UTC, phamann commented
@spiralman apologies, I also wanted to confirm @philippschulte is happy with this before merging.

2020-01-22 16:50 UTC, philippschulte approved these changes
@spiralman the changes look good to me! Thanks for also including the tests! I'll reach out to Hashicorp to request a new release.

2020-01-22 16:50 UTC, merged

2020-01-22 17:17 UTC, spiralman commented
Great, thanks very much @philippschulte and @phamann!