Add configuration for server side encryption
fastly/terraform-provider-fastly pull request #206
Opened 2020-01-24 23:22 UTC by pmmenzel

Depends on https://github.com/fastly/go-fastly/pull/144

2020-02-19 23:41 UTC, pmmenzel commented
@philippschulte You helped shepherd my go-fastly PR, so thought it would be most reasonable to ping you on this.   

The travis CI build is failing but when run make test locally, things seem good.  The failures seem to indicate that the CI environment may not have the latest go-fastly module even though I assumed that came from vendor dirs within the repo directly.  Any ideas? 

Please let me know if there's something I'm missing or need to do.    Thank you.

2020-02-20 11:27 UTC, phamann requested changes
Hey @pmmenzel, thank you for your contribution. Looks good to me other than some minor changes to the the description fields.

With regards to CI failures and the `gofastly` upgrade. You've updated the `go.mod` file, but as we vendor the dependencies, you also need to run `go mod vendor` to persist the module files to the `vendor` directory. This should then commit the upgrade (in a separate commit please) and CI should then pass.

2020-02-20 11:27 UTC, phamann commented on fastly/resource_fastly_service_v1.go
> +							Description:  "Specify where type of server side encryption should be used.",
Fix typo `s/where/what/` and please detail what the value can be, i.e. either `AES256` or `aws:kms`.

```suggestion
							Description:  "Specify what type of server side encryption should be used. Can be either `AES256` or `aws:kms`.",
```

2020-02-20 11:27 UTC, phamann commented on fastly/resource_fastly_service_v1.go
> +						},
Please add a `Description` field to this. This is the text we use in our [API docs](https://docs.fastly.com/api/logging#api-section-logging_s3):

> Optional server-side KMS Key Id. Must be set if `server_side_encryption` is set to `aws:kms`.

2020-02-20 11:27 UTC, phamann commented on fastly/validators.go
> +		"aws:kms",
It would be good to use the `gofastly` constants here such as `gofastly.S3ServerSideEncryptionAES`, like you have in the switch statement above.

2020-02-20 19:54 UTC, pmmenzel commented
> Hey @pmmenzel, thank you for your contribution. Looks good to me other than some minor changes to the the description fields.
> 
> With regards to CI failures and the `gofastly` upgrade. You've updated the `go.mod` file, but as we vendor the dependencies, you also need to run `go mod vendor` to persist the module files to the `vendor` directory. This should then commit the upgrade (in a separate commit please) and CI should then pass.

@phamann Thanks for the feedback as I'm still picking up the intricacies of golang.

2020-02-21 00:49 UTC, pmmenzel commented
@phamann So, I've spent several hours trying to figure out how to use the `gofastly.S3ServerSideEncryption{AES,KMS}` within the validator but have been running into pits of despair with my novice golang skills. 

When switching to use those constants I can no longer use the `validation.StringInSlice` function since it's no longer of type `string`.  So instead I tried to create and return a generic function (similar to what I saw being done in the `valdiation.go` file).  However I ran into further issues related to the `schema.SchemaValidateFunc` and so on.  

I'm really lost at the moment and could use some guidance.

2020-02-27 20:58 UTC, pmmenzel commented
Alright, finally figured out how to get around some of the issues I was running into and have a passing build.

2020-03-06 00:57 UTC, pmmenzel commented
@phamann Just bubbling this up again.   Thank you.

2020-03-18 15:46 UTC, phamann approved these changes
:+1: LGTM

2020-03-18 15:46 UTC, phamann commented on fastly/resource_fastly_service_v1.go
> +							Description: "Optional server-side KMS Key Id. Must be set if server_side_encryption is set to aws:kms",
```suggestion
							Description: "Optional server-side KMS Key Id. Must be set if server_side_encryption is set to `aws:kms`",
```

2020-03-18 16:56 UTC, pmmenzel commented
@phamann Committed your last suggested change.  Please merge at your convenience.  Thanks again!

2020-03-20 15:40 UTC, phamann requested changes
Apologies @pmmenzel a couple of things I noticed whilst testing this. Thank you for your patience on this PR. I promise these are the last changes :)

2020-03-20 15:40 UTC, phamann commented on fastly/resource_fastly_service_v1.go
> +				case "AES256":
```suggestion
				case string(gofastly.S3ServerSideEncryptionAES):
```

2020-03-20 15:40 UTC, phamann commented on fastly/validators.go
> +		string(gofastly.S3ServerSideEncryptionAES),
Looks like a copy paste error

```suggestion
		string(gofastly.S3ServerSideEncryptionKMS),
```

2020-03-20 15:40 UTC, phamann commented on fastly/resource_fastly_service_v1.go
> +				case "aws:kms":
```suggestion
				case string(gofastly.S3ServerSideEncryptionKMS):
```

2020-03-20 15:41 UTC, phamann commented
Lastly I would like @philippschulte to confirm he's happy and merge.

2020-03-25 07:49 UTC, philippschulte requested changes

2020-03-25 07:49 UTC, philippschulte commented on fastly/validators.go
> +
All validators are unit tested. Please add a table test for your new validator to `fastly/validators_test.go`.

2020-03-25 07:49 UTC, philippschulte commented on go.mod
> +	github.com/fastly/go-fastly v1.6.0
Please provide me the `go mod` commands you have used in order to upgrade the `go-fastly` dependency. As recommended by the [docs](https://github.com/golang/go/wiki/Modules#how-to-upgrade-and-downgrade-dependencies) a common starting point when upgrading a dependency is to do `go get <dependency>` or `go get <dependency>@latest`.

These are the commands I recommend to use when updating a dependency:

```
$ go get <package>@latest
$ go mod vendor
$ go mod tidy
```

When you upgrade dependencies it is also always good to run the integration test suite and to document the results in the PR like [here](https://github.com/terraform-providers/terraform-provider-fastly/pull/191) for example (please keep in mind that it takes about 30 to 45 minutes to run the suite). Let me know if you need help to run the suite.

2020-03-26 07:28 UTC, philippschulte commented on go.mod
> +	github.com/fastly/go-fastly v1.6.0
@pmmenzel I did run the acceptance tests:

<details><summary>Acceptance Test Results</summary>
<p>

```bash
$ make testacc 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v  -timeout 120m -ldflags="-X=github.com/terraform-providers/terraform-provider-fastly/version.ProviderVersion=acc"
?   	github.com/terraform-providers/terraform-provider-fastly	[no test files]
=== RUN   TestUserAgentContainsProviderVersion
--- PASS: TestUserAgentContainsProviderVersion (0.00s)
=== RUN   TestAccFastlyIPRanges
--- PASS: TestAccFastlyIPRanges (0.40s)
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestResourceFastlyFlattenAclEntries
--- PASS: TestResourceFastlyFlattenAclEntries (0.00s)
=== RUN   TestAccFastlyServiceAclEntriesV1_create
--- PASS: TestAccFastlyServiceAclEntriesV1_create (32.05s)
=== RUN   TestAccFastlyServiceAclEntriesV1_update
--- PASS: TestAccFastlyServiceAclEntriesV1_update (71.12s)
=== RUN   TestAccFastlyServiceAclEntriesV1_update_additional_fields
--- PASS: TestAccFastlyServiceAclEntriesV1_update_additional_fields (67.05s)
=== RUN   TestAccFastlyServiceAclEntriesV1_delete
--- PASS: TestAccFastlyServiceAclEntriesV1_delete (63.35s)
=== RUN   TestAccFastlyServiceAclEntriesV1_import
--- PASS: TestAccFastlyServiceAclEntriesV1_import (31.78s)
=== RUN   TestAccFastlyServiceAclEntriesV1_process_1001_entries
--- PASS: TestAccFastlyServiceAclEntriesV1_process_1001_entries (77.66s)
=== RUN   TestResourceFastlyFlattenDictionaryItems
--- PASS: TestResourceFastlyFlattenDictionaryItems (0.00s)
=== RUN   TestAccFastlyServiceDictionaryItemV1_create
--- PASS: TestAccFastlyServiceDictionaryItemV1_create (31.08s)
=== RUN   TestAccFastlyServiceDictionaryItemV1_create_dynamic
--- PASS: TestAccFastlyServiceDictionaryItemV1_create_dynamic (30.66s)
=== RUN   TestAccFastlyServiceDictionaryItemV1_update
--- PASS: TestAccFastlyServiceDictionaryItemV1_update (68.41s)
=== RUN   TestAccFastlyServiceDictionaryItemV1_external_item_is_removed
--- PASS: TestAccFastlyServiceDictionaryItemV1_external_item_is_removed (50.09s)
=== RUN   TestAccFastlyServiceDictionaryItemV1_external_item_deleted
--- PASS: TestAccFastlyServiceDictionaryItemV1_external_item_deleted (62.93s)
=== RUN   TestAccFastlyServiceDictionaryItemV1_batch_1001_items
--- PASS: TestAccFastlyServiceDictionaryItemV1_batch_1001_items (55.40s)
=== RUN   TestAccFastlyServiceDictionaryItemV1_import
--- PASS: TestAccFastlyServiceDictionaryItemV1_import (30.04s)
=== RUN   TestAccFastlyServiceDynamicSnippetContentV1_create
--- PASS: TestAccFastlyServiceDynamicSnippetContentV1_create (30.67s)
=== RUN   TestAccFastlyServiceDynamicSnippetContentV1_update
--- PASS: TestAccFastlyServiceDynamicSnippetContentV1_update (67.74s)
=== RUN   TestAccFastlyServiceDynamicSnippetContentV1_external_snippet_is_removed
--- PASS: TestAccFastlyServiceDynamicSnippetContentV1_external_snippet_is_removed (68.06s)
=== RUN   TestAccFastlyServiceDynamicSnippetContentV1_normal_snippet_is_not_removed
--- PASS: TestAccFastlyServiceDynamicSnippetContentV1_normal_snippet_is_not_removed (61.77s)
=== RUN   TestAccFastlyServiceDynamicSnippetContentV1_import
--- PASS: TestAccFastlyServiceDynamicSnippetContentV1_import (35.45s)
=== RUN   TestResourceFastlyFlattenAcl
--- PASS: TestResourceFastlyFlattenAcl (0.00s)
=== RUN   TestAccFastlyServiceV1_acl
--- PASS: TestAccFastlyServiceV1_acl (29.67s)
=== RUN   TestResourceFastlyFlattenBigQuery
--- PASS: TestResourceFastlyFlattenBigQuery (0.23s)
=== RUN   TestAccFastlyServiceV1_bigquerylogging
--- PASS: TestAccFastlyServiceV1_bigquerylogging (28.05s)
=== RUN   TestAccFastlyServiceV1_bigquerylogging_env
--- PASS: TestAccFastlyServiceV1_bigquerylogging_env (27.57s)
=== RUN   TestResourceFastlyFlattenBlobStorage
--- PASS: TestResourceFastlyFlattenBlobStorage (0.00s)
=== RUN   TestAccFastlyServiceV1_blobstoragelogging_basic
--- PASS: TestAccFastlyServiceV1_blobstoragelogging_basic (62.48s)
=== RUN   TestAccFastlyServiceV1_blobstoragelogging_default
--- PASS: TestAccFastlyServiceV1_blobstoragelogging_default (30.51s)
=== RUN   TestAccFastlyServiceV1_blobstoragelogging_env
--- PASS: TestAccFastlyServiceV1_blobstoragelogging_env (27.61s)
=== RUN   TestResourceFastlyFlattenCacheSettings
--- PASS: TestResourceFastlyFlattenCacheSettings (0.00s)
=== RUN   TestAccFastlyServiceV1CacheSetting_basic
--- PASS: TestAccFastlyServiceV1CacheSetting_basic (60.96s)
=== RUN   TestResourceFastlyFlattenConditions
--- PASS: TestResourceFastlyFlattenConditions (0.00s)
=== RUN   TestAccFastlyServiceV1_conditional_basic
--- PASS: TestAccFastlyServiceV1_conditional_basic (27.56s)
=== RUN   TestResourceFastlyFlattenDictionary
--- PASS: TestResourceFastlyFlattenDictionary (0.00s)
=== RUN   TestAccFastlyServiceV1_dictionary
--- PASS: TestAccFastlyServiceV1_dictionary (27.47s)
=== RUN   TestAccFastlyServiceV1_dictionary_write_only
--- PASS: TestAccFastlyServiceV1_dictionary_write_only (26.28s)
=== RUN   TestAccFastlyServiceV1_dictionary_update_name
--- PASS: TestAccFastlyServiceV1_dictionary_update_name (61.96s)
=== RUN   TestAccFastlyServiceV1_dictionary_update_write_only
--- PASS: TestAccFastlyServiceV1_dictionary_update_write_only (60.45s)
=== RUN   TestResourceFastlyFlattenDirectors
--- PASS: TestResourceFastlyFlattenDirectors (0.00s)
=== RUN   TestAccFastlyServiceV1_directors_basic
--- PASS: TestAccFastlyServiceV1_directors_basic (70.49s)
=== RUN   TestResourceFastlyFlattenDynamicSnippets
--- PASS: TestResourceFastlyFlattenDynamicSnippets (0.00s)
=== RUN   TestAccFastlyServiceV1DynamicSnippet_basic
--- PASS: TestAccFastlyServiceV1DynamicSnippet_basic (59.69s)
=== RUN   TestResourceFastlyFlattenGCS
--- PASS: TestResourceFastlyFlattenGCS (0.14s)
=== RUN   TestAccFastlyServiceV1_gcslogging
--- PASS: TestAccFastlyServiceV1_gcslogging (27.60s)
=== RUN   TestAccFastlyServiceV1_gcslogging_env
--- PASS: TestAccFastlyServiceV1_gcslogging_env (26.93s)
=== RUN   TestResourceFastlyFlattenGzips
--- PASS: TestResourceFastlyFlattenGzips (0.00s)
=== RUN   TestAccFastlyServiceV1_gzips_basic
--- PASS: TestAccFastlyServiceV1_gzips_basic (60.59s)
=== RUN   TestResourceFastlyFlattenHeaders
--- PASS: TestResourceFastlyFlattenHeaders (0.00s)
=== RUN   TestFastlyServiceV1_BuildHeaders
--- PASS: TestFastlyServiceV1_BuildHeaders (0.00s)
=== RUN   TestAccFastlyServiceV1_headers_basic
--- PASS: TestAccFastlyServiceV1_headers_basic (59.69s)
=== RUN   TestResourceFastlyFlattenHealthChecks
--- PASS: TestResourceFastlyFlattenHealthChecks (0.00s)
=== RUN   TestAccFastlyServiceV1_healthcheck_basic
--- PASS: TestAccFastlyServiceV1_healthcheck_basic (57.78s)
=== RUN   TestResourceFastlyFlattenLogentries
--- PASS: TestResourceFastlyFlattenLogentries (0.00s)
=== RUN   TestAccFastlyServiceV1_logentries_basic
--- PASS: TestAccFastlyServiceV1_logentries_basic (62.31s)
=== RUN   TestAccFastlyServiceV1_logentries_formatVersion
--- PASS: TestAccFastlyServiceV1_logentries_formatVersion (27.75s)
=== RUN   TestResourceFastlyFlattenPapertrail
--- PASS: TestResourceFastlyFlattenPapertrail (0.00s)
=== RUN   TestAccFastlyServiceV1_papertrail_basic
--- PASS: TestAccFastlyServiceV1_papertrail_basic (59.45s)
=== RUN   TestResourceFastlyFlattenRequestSettings
--- PASS: TestResourceFastlyFlattenRequestSettings (0.00s)
=== RUN   TestAccFastlyServiceV1RequestSetting_basic
--- PASS: TestAccFastlyServiceV1RequestSetting_basic (29.27s)
=== RUN   TestResourceFastlyFlattenResponseObjects
--- PASS: TestResourceFastlyFlattenResponseObjects (0.00s)
=== RUN   TestAccFastlyServiceV1_response_object_basic
--- PASS: TestAccFastlyServiceV1_response_object_basic (60.49s)
=== RUN   TestAccFastlyServiceV1_s3logging_basic
--- PASS: TestAccFastlyServiceV1_s3logging_basic (61.39s)
=== RUN   TestAccFastlyServiceV1_s3logging_domain_default
--- PASS: TestAccFastlyServiceV1_s3logging_domain_default (27.39s)
=== RUN   TestAccFastlyServiceV1_s3logging_s3_env
--- PASS: TestAccFastlyServiceV1 [...]

2020-03-30 16:44 UTC, philippschulte commented
@pmmenzel your PR is ready to merge after you add the table test for your new validator. If you're to busy we can add the test too. Just let us know. Thank you

2020-03-30 20:27 UTC, philippschulte commented
@pmmenzel I have added the missing table test for your new validator. Thank you for your patience on this PR and your contribution. The changes of this PR will be part of the next release. Hopefully tomorrow 🙏

2020-03-30 20:27 UTC, merged