Add ability to terraform fastly users
fastly/terraform-provider-fastly pull request #214
Opened 2020-04-01 15:36 UTC by sbfaulkner

related: #134 

(I think) this PR adds support for basic user crud operations -- and updates the docs

a separate PR would be needed add support for configuring service access for the "engineer" role (and probably requires additional support in go-fastly)

please let me know what else might be needed to get this minimum viable support merged @philippschulte :-)

2020-04-01 15:54 UTC, sbfaulkner commented
confused about why travis is failing... since go-fastly was updated to latest in an earlier PR :-(

2020-04-01 16:07 UTC, sbfaulkner commented
re: travis... looks like it's because some of the dependencies now require go 1.12 and 1.13

2020-04-01 20:49 UTC, sbfaulkner commented
I think maybe `go-fastly` is unintentionally requiring go 1.13 ... https://github.com/fastly/go-fastly/pull/148/files#r401898350

2020-04-01 20:52 UTC, chenrui333 commented
isn't this provider also using 1.13?
https://github.com/terraform-providers/terraform-provider-fastly/blob/master/go.mod#L10

2020-04-01 20:58 UTC, sbfaulkner commented
@chenrui333 everything was working locally (where I was using 1.13)... but CI uses multiple versions (like the pkg does)

testing locally using 1.11 I get...

```
$ go version
go version go1.11 darwin/amd64
$ go vet .
go build github.com/terraform-providers/terraform-provider-fastly/version: module requires Go 1.13
```

2020-04-01 21:02 UTC, chenrui333 commented
Let me help with the CI a little bit, this travis config is already out of sync with the `go.mod` file

2020-04-03 13:32 UTC, phamann requested changes
Looking good @sbfaulkner, thank you for your contribution. A few minor changes requested. Would also be good to see the acceptance tests output.

2020-04-03 13:32 UTC, phamann commented on fastly/resource_fastly_user_v1.go
> +				Description:  "The user-assigned permissions role. Can be `user`, `billing`, `engineer`, or `superuser`.",
Please add the default in this string, as you have in the website documentation.

2020-04-03 13:32 UTC, phamann commented on fastly/resource_fastly_user_v1_test.go
> +	login := fmt.Sprintf("tf-test-%s@example.com", acctest.RandString(10))
You don't seem to be creating a second login/email as you have with role and name. Is this intentional? As unlike role and name, the login is the one property which needs to be globally unique in Fastly.

2020-04-03 13:37 UTC, sbfaulkner commented on fastly/resource_fastly_user_v1.go
> +				Description:  "The user-assigned permissions role. Can be `user`, `billing`, `engineer`, or `superuser`.",
✅ 652786f

2020-04-03 14:04 UTC, sbfaulkner commented on fastly/resource_fastly_user_v1_test.go
> +	login := fmt.Sprintf("tf-test-%s@example.com", acctest.RandString(10))
the current implementation of Update in go-fastly does not support updating the Login

I had originally done this intentionally, but question it now

I can submit a PR to update go-fastly to support updating Login as well and then update this PR to use it :-)

2020-04-03 17:28 UTC, sbfaulkner commented on fastly/resource_fastly_user_v1_test.go
> +	login := fmt.Sprintf("tf-test-%s@example.com", acctest.RandString(10))
hrm... or maybe not... updating the Login via API requires the password too, so not sure this is even possible

2020-04-06 13:59 UTC, sbfaulkner commented on fastly/resource_fastly_user_v1_test.go
> +	login := fmt.Sprintf("tf-test-%s@example.com", acctest.RandString(10))
I guess the API "limitation" of requiring the password will mean that a change in login will necessitate a full recreation of the resource

2020-04-06 15:34 UTC, sbfaulkner commented on fastly/resource_fastly_user_v1_test.go
> +	login := fmt.Sprintf("tf-test-%s@example.com", acctest.RandString(10))
updated to force a new resource when the login changes as a work-around to the API "limitation"
9f2e834

2020-04-06 17:04 UTC, phamann commented
@sbfaulkner I have now merged @chenrui333's PR #215 so hopefully your tests may pass now if you want to try and re-run.

2020-04-07 15:52 UTC, sbfaulkner commented
@phamann thanks... it does in fact pass now, and I think I've addressed all points from your review :-)

2020-04-07 15:57 UTC, chenrui333 commented
glad it works out!

2020-04-08 15:15 UTC, phamann commented
I re-ran the acceptance tests with your new changes and all are passing. 

```
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v  -timeout 120m -ldflags="-X=github.com/terraform-providers/terraform-provider-fastly/version.ProviderVersion=acc"
?   	github.com/terraform-providers/terraform-provider-fastly	[no test files]
=== RUN   TestUserAgentContainsProviderVersion
--- PASS: TestUserAgentContainsProviderVersion (0.00s)
=== RUN   TestAccFastlyIPRanges
--- PASS: TestAccFastlyIPRanges (1.01s)
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestResourceFastlyFlattenAclEntries
--- PASS: TestResourceFastlyFlattenAclEntries (0.00s)
=== RUN   TestAccFastlyServiceAclEntriesV1_create
--- PASS: TestAccFastlyServiceAclEntriesV1_create (50.77s)
=== RUN   TestAccFastlyServiceAclEntriesV1_update
--- PASS: TestAccFastlyServiceAclEntriesV1_update (103.16s)
=== RUN   TestAccFastlyServiceAclEntriesV1_update_additional_fields
--- PASS: TestAccFastlyServiceAclEntriesV1_update_additional_fields (85.53s)
=== RUN   TestAccFastlyServiceAclEntriesV1_delete
--- PASS: TestAccFastlyServiceAclEntriesV1_delete (90.22s)
=== RUN   TestAccFastlyServiceAclEntriesV1_import
--- PASS: TestAccFastlyServiceAclEntriesV1_import (45.78s)
=== RUN   TestAccFastlyServiceAclEntriesV1_process_1001_entries
--- PASS: TestAccFastlyServiceAclEntriesV1_process_1001_entries (89.47s)
=== RUN   TestResourceFastlyFlattenDictionaryItems
--- PASS: TestResourceFastlyFlattenDictionaryItems (0.00s)
=== RUN   TestAccFastlyServiceDictionaryItemV1_create
--- PASS: TestAccFastlyServiceDictionaryItemV1_create (39.40s)
=== RUN   TestAccFastlyServiceDictionaryItemV1_create_dynamic
--- PASS: TestAccFastlyServiceDictionaryItemV1_create_dynamic (39.60s)
=== RUN   TestAccFastlyServiceDictionaryItemV1_update
--- PASS: TestAccFastlyServiceDictionaryItemV1_update (80.10s)
=== RUN   TestAccFastlyServiceDictionaryItemV1_external_item_is_removed
--- PASS: TestAccFastlyServiceDictionaryItemV1_external_item_is_removed (70.66s)
=== RUN   TestAccFastlyServiceDictionaryItemV1_external_item_deleted
--- PASS: TestAccFastlyServiceDictionaryItemV1_external_item_deleted (130.69s)
=== RUN   TestAccFastlyServiceDictionaryItemV1_batch_1001_items
--- PASS: TestAccFastlyServiceDictionaryItemV1_batch_1001_items (66.22s)
=== RUN   TestAccFastlyServiceDictionaryItemV1_import
--- PASS: TestAccFastlyServiceDictionaryItemV1_import (36.47s)
=== RUN   TestAccFastlyServiceDynamicSnippetContentV1_create
--- PASS: TestAccFastlyServiceDynamicSnippetContentV1_create (37.89s)
=== RUN   TestAccFastlyServiceDynamicSnippetContentV1_update
--- PASS: TestAccFastlyServiceDynamicSnippetContentV1_update (75.87s)
=== RUN   TestAccFastlyServiceDynamicSnippetContentV1_external_snippet_is_removed
--- PASS: TestAccFastlyServiceDynamicSnippetContentV1_external_snippet_is_removed (84.72s)
=== RUN   TestAccFastlyServiceDynamicSnippetContentV1_normal_snippet_is_not_removed
--- PASS: TestAccFastlyServiceDynamicSnippetContentV1_normal_snippet_is_not_removed (75.31s)
=== RUN   TestAccFastlyServiceDynamicSnippetContentV1_import
--- PASS: TestAccFastlyServiceDynamicSnippetContentV1_import (36.29s)
=== RUN   TestResourceFastlyFlattenAcl
--- PASS: TestResourceFastlyFlattenAcl (0.00s)
=== RUN   TestAccFastlyServiceV1_acl
--- PASS: TestAccFastlyServiceV1_acl (34.28s)
=== RUN   TestResourceFastlyFlattenBigQuery
--- PASS: TestResourceFastlyFlattenBigQuery (0.17s)
=== RUN   TestAccFastlyServiceV1_bigquerylogging
--- PASS: TestAccFastlyServiceV1_bigquerylogging (32.47s)
=== RUN   TestAccFastlyServiceV1_bigquerylogging_env
--- PASS: TestAccFastlyServiceV1_bigquerylogging_env (34.84s)
=== RUN   TestResourceFastlyFlattenBlobStorage
--- PASS: TestResourceFastlyFlattenBlobStorage (0.00s)
=== RUN   TestAccFastlyServiceV1_blobstoragelogging_basic
--- PASS: TestAccFastlyServiceV1_blobstoragelogging_basic (87.34s)
=== RUN   TestAccFastlyServiceV1_blobstoragelogging_default
--- PASS: TestAccFastlyServiceV1_blobstoragelogging_default (32.97s)
=== RUN   TestAccFastlyServiceV1_blobstoragelogging_env
--- PASS: TestAccFastlyServiceV1_blobstoragelogging_env (38.35s)
=== RUN   TestResourceFastlyFlattenCacheSettings
--- PASS: TestResourceFastlyFlattenCacheSettings (0.00s)
=== RUN   TestAccFastlyServiceV1CacheSetting_basic
--- PASS: TestAccFastlyServiceV1CacheSetting_basic (72.47s)
=== RUN   TestResourceFastlyFlattenConditions
--- PASS: TestResourceFastlyFlattenConditions (0.00s)
=== RUN   TestAccFastlyServiceV1_conditional_basic
--- PASS: TestAccFastlyServiceV1_conditional_basic (32.68s)
=== RUN   TestResourceFastlyFlattenDictionary
--- PASS: TestResourceFastlyFlattenDictionary (0.00s)
=== RUN   TestAccFastlyServiceV1_dictionary
--- PASS: TestAccFastlyServiceV1_dictionary (33.85s)
=== RUN   TestAccFastlyServiceV1_dictionary_write_only
--- PASS: TestAccFastlyServiceV1_dictionary_write_only (32.78s)
=== RUN   TestAccFastlyServiceV1_dictionary_update_name
--- PASS: TestAccFastlyServiceV1_dictionary_update_name (77.07s)
=== RUN   TestAccFastlyServiceV1_dictionary_update_write_only
--- PASS: TestAccFastlyServiceV1_dictionary_update_write_only (74.95s)
=== RUN   TestResourceFastlyFlattenDirectors
--- PASS: TestResourceFastlyFlattenDirectors (0.00s)
=== RUN   TestAccFastlyServiceV1_directors_basic
--- PASS: TestAccFastlyServiceV1_directors_basic (79.87s)
=== RUN   TestResourceFastlyFlattenDynamicSnippets
--- PASS: TestResourceFastlyFlattenDynamicSnippets (0.00s)
=== RUN   TestAccFastlyServiceV1DynamicSnippet_basic
--- PASS: TestAccFastlyServiceV1DynamicSnippet_basic (72.19s)
=== RUN   TestResourceFastlyFlattenGCS
--- PASS: TestResourceFastlyFlattenGCS (0.08s)
=== RUN   TestAccFastlyServiceV1_gcslogging
--- PASS: TestAccFastlyServiceV1_gcslogging (34.45s)
=== RUN   TestAccFastlyServiceV1_gcslogging_env
--- PASS: TestAccFastlyServiceV1_gcslogging_env (34.61s)
=== RUN   TestResourceFastlyFlattenGzips
--- PASS: TestResourceFastlyFlattenGzips (0.00s)
=== RUN   TestAccFastlyServiceV1_gzips_basic
--- PASS: TestAccFastlyServiceV1_gzips_basic (75.28s)
=== RUN   TestResourceFastlyFlattenHeaders
--- PASS: TestResourceFastlyFlattenHeaders (0.00s)
=== RUN   TestFastlyServiceV1_BuildHeaders
--- PASS: TestFastlyServiceV1_BuildHeaders (0.00s)
=== RUN   TestAccFastlyServiceV1_headers_basic
--- PASS: TestAccFastlyServiceV1_headers_basic (71.94s)
=== RUN   TestResourceFastlyFlattenHealthChecks
--- PASS: TestResourceFastlyFlattenHealthChecks (0.00s)
=== RUN   TestAccFastlyServiceV1_healthcheck_basic
--- PASS: TestAccFastlyServiceV1_healthcheck_basic (68.42s)
=== RUN   TestResourceFastlyFlattenLogentries
--- PASS: TestResourceFastlyFlattenLogentries (0.00s)
=== RUN   TestAccFastlyServiceV1_logentries_basic
--- PASS: TestAccFastlyServiceV1_logentries_basic (72.95s)
=== RUN   TestAccFastlyServiceV1_logentries_formatVersion
--- PASS: TestAccFastlyServiceV1_logentries_formatVersion (34.63s)
=== RUN   TestResourceFastlyFlattenPapertrail
--- PASS: TestResourceFastlyFlattenPapertrail (0.00s)
=== RUN   TestAccFastlyServiceV1_papertrail_basic
--- PASS: TestAccFastlyServiceV1_papertrail_basic (96.45s)
=== RUN   TestResourceFastlyFlattenRequestSettings
--- PASS: TestResourceFastlyFlattenRequestSettings (0.00s)
=== RUN   TestAccFastlyServiceV1RequestSetting_basic
--- PASS: TestAccFastlyServiceV1RequestSetting_basic (64.78s)
=== RUN   TestResourceFastlyFlattenResponseObjects
--- PASS: TestResourceFastlyFlattenResponseObjects (0.00s)
=== RUN   TestAccFastlyServiceV1_response_object_basic
--- PASS: TestAccFastlyServiceV1_response_object_basic (83.93s)
=== RUN   TestAccFastlyServiceV1_s3logging_basic
--- PASS: TestAccFastlyServiceV1_s3logging_basic (74.78s)
=== RUN   TestAccFastlyServiceV1_s3logging_domain_default
--- PASS: TestAccFastlyServiceV1_s3logging_domain_default (40.94s)
=== RUN   TestAccFastlyServiceV1_s3logging_s3_env
--- PASS: TestAccFastlyServiceV1_s3logging_s3_env (37.30s)
=== RUN   TestAc [...]

2020-04-08 15:22 UTC, phamann approved these changes
:+1: This is looking great @sbfaulkner , I added one minor suggestion to the website documentation, but other than that I am happy to merge.

2020-04-08 15:22 UTC, phamann commented on website/docs/r/user_v1.html.markdown
> +* `role` - (Optional) The role of this user. Can be `user` (the default), `billing`, `engineer`, or `superuser`.
```suggestion
* `role` - (Optional) The role of this user. Can be `user` (the default), `billing`, `engineer`, or `superuser`. For detailed information on the abilities granted to each role, see [Fastly's Documentation on User roles](https://docs.fastly.com/en/guides/configuring-user-roles-and-permissions#user-roles-and-what-they-can-do).
```

2020-04-08 15:50 UTC, sbfaulkner commented on website/docs/r/user_v1.html.markdown
> +* `role` - (Optional) The role of this user. Can be `user` (the default), `billing`, `engineer`, or `superuser`.
thanks - commited your suggested change

2020-04-08 15:52 UTC, sbfaulkner commented
thanks @phamann - if you can ping me once you cut a new release, we'll start using it right away :-)

2020-04-14 12:11 UTC, merged