Update changelog for release (v0.17.0)
fastly/terraform-provider-fastly pull request #266
Opened 2020-06-19 13:21 UTC by mccurdyc

2020-06-19 13:24 UTC, mccurdyc commented
Force-pushed a format / order fix.

2020-06-19 13:25 UTC, mccurdyc commented
Force-pushed another order fix.

2020-06-19 13:27 UTC, mccurdyc commented on CHANGELOG.md
> +* resource/fastly_service_v1/splunk: Use `trimSpaceStateFunc` to trim leading and trailing whitespace from the `tls_ca_cert` field ([#264](https://github.com/terraform-providers/terraform-provider-fa
@phamann These could introduce a new diff of state for customers. Would remove a new line.

I don't think this is technically a breaking change, but does introduce a state change just from updating your provider version.

Just something to think about.

2020-06-19 13:29 UTC, mccurdyc commented
I'll add a line in the NOTES with links to PRs updating docs.

2020-06-22 18:58 UTC, phamann requested changes
LGTM other than the date

2020-06-22 18:58 UTC, phamann commented on CHANGELOG.md
> +## 0.17.0 (June 19, 2020)
```suggestion
## 0.17.0 (June 22, 2020)
```

2020-06-22 19:05 UTC, phamann approved these changes
:+1: LGTM

2020-06-22 20:24 UTC, merged