Add Kinesis logging support
fastly/terraform-provider-fastly pull request #351
Opened 2021-01-05 20:35 UTC by MerlinDMC

## Proposed Change(s)

- Updates `go-fastly` to version `v2.1.0` to support Kinesis.
- Adds support for provisioning Kinesis logging endpoints.
- Updates `fastly_service_v1` and `fastly_service_compute` docs to reflect the change.

## Relevant Link(s) / Doc(s)

- [API Docs](https://developer.fastly.com/reference/api/logging/kinesis/)
- [Relevant Fastly API Go client library file](https://github.com/fastly/go-fastly/blob/master/fastly/kinesis.go)

## Validation

```shell
export FASTLY_API_KEY="foo"; export TF_ACC=1; make testacc TESTARGS='-run=[kK]inesis'
```

fixes #350

2021-01-06 18:15 UTC, Integralist requested changes
👋🏻 I ran your branch/tests locally and found they were failing so I noticed this issue in the code that when updated would cause the tests to pass.

I'll give another proper/full review tomorrow.

Thanks.

2021-01-06 18:15 UTC, Integralist commented on fastly/resource_fastly_service_compute.go
> +		NewServiceLoggingKinesis(vclAttributes),
```suggestion
		NewServiceLoggingKinesis(computeAttributes),
```

2021-01-07 11:19 UTC, Integralist reviewed
👋🏻 I noticed just a couple of minor corrections.

2021-01-07 11:19 UTC, Integralist commented on website/docs/r/service_compute.html.markdown
> +* `name` - (Required) The unique name of the Logshuttle logging endpoint.
```suggestion
* `name` - (Required) The unique name of the Kinesis logging endpoint.
```

2021-01-07 11:19 UTC, Integralist commented on website/docs/r/service_v1.html.markdown
> +* `name` - (Required) The unique name of the Logshuttle logging endpoint.
```suggestion
* `name` - (Required) The unique name of the Kinesis logging endpoint.
```

2021-01-07 11:19 UTC, Integralist commented on website_src/docs/r/arguments/logging_kinesis.markdown.tmpl
> +* `name` - (Required) The unique name of the Logshuttle logging endpoint.
```suggestion
* `name` - (Required) The unique name of the Kinesis logging endpoint.
```

2021-01-07 11:30 UTC, MerlinDMC commented
Copy and Paste 😞

2021-01-07 11:43 UTC, Integralist approved these changes
Awesome @MerlinDMC thank you for taking the time to put this PR together! 

This looks good to me.

I'm now running the full test suite on your branch before I merge, but unfortunately it can take many hours to complete (we're working on fixing that btw).

2021-01-08 09:28 UTC, merged

2021-01-08 09:39 UTC, MerlinDMC commented
👍 Thanks for taking the time to review and test it. We're looking forward to test the logging stream via Kinesis 😉