Add stale if error settings
fastly/terraform-provider-fastly pull request #432
Opened 2021-06-25 21:38 UTC by bridgetlane

2021-06-28 16:37 UTC, Integralist commented on fastly/block_fastly_service_v1_settings.go
> +		Description: "The default hostname",
Need to update the description.

2021-06-28 16:37 UTC, Integralist commented on fastly/block_fastly_service_v1_settings.go
> +		Description: "The default hostname",
Need to update the description.

2021-06-28 16:37 UTC, Integralist commented on fastly/resource_fastly_service_compute_test.go
> +						"fastly_service_compute.foo", "stale_if_error", "true"),
I presume we also want to validate that `stale_if_error_ttl` is set to zero by the configuration (as the default value of `43200 ` is being validated in the following new test).

2021-06-28 16:37 UTC, Integralist commented on fastly/resource_fastly_service_compute_test.go
> +						"fastly_service_compute.foo", "stale_if_error", "true"),
Oh I see you have another test for that (`TestAccFastlyServiceCompute_createZeroDefaultTTL`) but maybe worth still adding a check for the attribute here too?

2021-06-28 17:11 UTC, bridgetlane commented
Thank you for the review @Integralist! Updated accordingly

2021-06-29 08:26 UTC, Integralist reviewed
Two small suggestions @bridgetlane

2021-06-29 08:26 UTC, Integralist commented on fastly/block_fastly_service_v1_settings.go
> +		Description: "Whether or not stale if error should be true",
I would prefer us to use the same language as on the developer reference for consistency/accuracy:

> Enables serving a stale object if there is an error

2021-06-29 08:26 UTC, Integralist commented on fastly/block_fastly_service_v1_settings.go
> +		Description: "The TTL for stale if error",
I would prefer us to use the same language as on the developer reference for consistency/accuracy:

> The default time-to-live (TTL) for serving the stale object for the version

2021-06-30 08:31 UTC, Integralist requested changes

2021-06-30 08:31 UTC, Integralist commented on fastly/resource_fastly_service_v1_test.go
> +						"fastly_service_v1.foo", "default_host", defaultHost),
@bridgetlane looks like a bad merge. I think you need an extra `resource.TestCheckResourceAttr(` added above this line.

2021-06-30 08:31 UTC, Integralist commented on fastly/resource_fastly_service_v1_test.go
> +						"fastly_service_v1.foo", "default_host", defaultHost),
that should hopefully fix all the other lint errors as I think they're all falling out from this first syntax error.

2021-07-01 15:57 UTC, Integralist approved these changes
This looks OK to me. @bridgetlane have you run the full test suite on this PR yet?

2021-09-07 11:07 UTC, Integralist commented
FYI I'm using go 1.17 and I needed to run `gofmt -w tools/tools.go` to update the build constraint flag so the latest format is supported:

```diff
+//go:build tools
 // +build tools
```

2021-09-07 12:17 UTC, Integralist commented
@bridgetlane @smaeda-ks 

Running the test suite I noticed: `TestAccFastlyServiceCompute_basic` is failing...

```
resource_fastly_service_compute_test.go:96: 
Step 1/2 error: Check failed: 
Check 5/11 error: fastly_service_compute.foo: 
Attribute ‘stale_if_error_ttl’ expected “43200”, got “0"
```

2021-09-21 22:56 UTC, smaeda-ks requested changes
@bridgetlane or @Integralist I've added some suggestions including fixes for test cases. Since I don't have write access to this repo I can't add commits. Can either of you review and apply those suggestions? Then we should be able to merge this. Thanks

2021-09-21 22:56 UTC, smaeda-ks commented on fastly/resource_fastly_service_compute_test.go
> +						"fastly_service_compute.foo", "stale_if_error_ttl", "43200"),
```suggestion
						"fastly_service_compute.foo", "stale_if_error_ttl", "0"),
```

this should be 0

2021-09-21 22:56 UTC, smaeda-ks commented on fastly/resource_fastly_service_v1_test.go
> +						"fastly_service_v1.foo", "default_ttl", "3400"),
```suggestion
						"fastly_service_v1.foo", "default_ttl", "3600"),
```

our default is 3600, not 3400 (considering `testAccServiceV1Config_default_host` config is not setting `default_ttl`)

2021-09-21 22:56 UTC, smaeda-ks commented on fastly/block_fastly_service_v1_settings.go
> +	opts.StaleIfErrorTTL = &val
```suggestion
```

2021-09-21 22:56 UTC, smaeda-ks commented on fastly/block_fastly_service_v1_settings.go
>  		DefaultTTL: uint(d.Get("default_ttl").(int)),
```suggestion
		DefaultTTL:      uint(d.Get("default_ttl").(int)),
		StaleIfErrorTTL: gofastly.Uint(uint(d.Get("stale_if_error_ttl").(int))),
```

2021-09-21 22:56 UTC, smaeda-ks commented on fastly/block_fastly_service_v1_settings.go
>  		DefaultTTL: uint(d.Get("default_ttl").(int)),
Can you also update the comment accordingly?
https://github.com/fastly/terraform-provider-fastly/blob/v0.35.0/fastly/block_fastly_service_v1_settings.go#L24-L25
something like:

```
		// We have the same default value that is provided by
		// the Fastly API, so it's safe to include here
```

2021-09-23 09:12 UTC, Integralist commented
To help expedite these changes I'm going to close this PR and it will be replaced by...
https://github.com/fastly/terraform-provider-fastly/pull/475

Both Bridget and Shohei are credited as the authors of the work respectively.

2021-09-23 09:12 UTC, closed without merging