Remove TLS subscriptions that 404 from state
fastly/terraform-provider-fastly pull request #479
Opened 2021-09-29 20:14 UTC by bendrucker

When a TLS subscription is removed outside of Terraform, currently it causes refreshes to fail

```
╷
│ Error: 404 - Not Found:
│ 
│     Title:  Not found
│     Detail: The subscription you requested was not found
```

Instead, the provider should remove these resources from state. This is handled in other resources but the exact implementation differs a bit by resource.

2021-10-03 21:00 UTC, smaeda-ks requested changes
Hi @bendrucker, thanks for the PR.

`tls_subscription_validation` is a virtual resource so I don't think it's worth adding this logic in there. Could you please undo that?

2021-10-04 17:55 UTC, bendrucker commented
Hey @smaeda-ks I thought it might still help address the following scenario:

1. I apply configuration that creates a `tls_subscription` and uses the validation resource to wait for completion
2. I delete the TLS subscription outside of Terraform
3. I re-apply the configuration


The result should be the same after steps 1 and 3. Without this logic in the validation resource, I expect the same error would occur on refresh during step 3, requiring `state rm` to proceed.

2021-10-06 09:17 UTC, smaeda-ks commented
ok, thanks. I'll give it a try and get back to you.

2021-10-15 11:11 UTC, smaeda-ks approved these changes
Added a commit to change the way to return the warning message (and removed nesting).

2021-10-15 11:21 UTC, merged