Make backends not required on compute@edge resource
fastly/terraform-provider-fastly pull request #563
Opened 2022-04-15 03:09 UTC by jmoney

Currently, the compute@edge resource requires at least one backend to create the resource however this is actually not required of compute@edge services.  Aligning the terraform resource with the compute@edge service.

2022-04-22 10:20 UTC, Integralist requested changes
👋🏻 Thanks for opening this PR (and your patience waiting for feedback).

The changes look good to me. 

I've pulled your branch locally and validated the changes manually (all works as expected). 

I've also run the complete integration test suite, which passes as well.

I have only one change request, which is to update the example `examples/resources/service_compute_basic_usage.tf` to remove the `backend` block and to regenerate the docs by running `make generate-docs`.

Thanks!

2022-04-22 22:06 UTC, jmoney commented
I updated the example file and regenerated the doc

2022-04-25 03:55 UTC, jmoney commented
Let me know if anything else is required for this @Integralist

2022-04-25 08:29 UTC, Integralist approved these changes

2022-04-25 08:38 UTC, merged